services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: news-postgres
      DB_PORT: "5432"
      NEWS_DB: news_db
      DB_ADMIN_DB: postgres
    command: ["python", "main.py", "--worker", "--bootstrap", "--poll_interval", "3"]
    networks:
      - news-stack-net

networks:
  news-stack-net:
    external: true
